// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOPKrLPVGFQ9oPBdwPltb3W2XKNBvopF0',
    appId: '1:1038468137679:web:595831fea370bdd2456dba',
    messagingSenderId: '1038468137679',
    projectId: 'careermatebd',
    authDomain: 'careermatebd.firebaseapp.com',
    storageBucket: 'careermatebd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzOLTsZMdGSbRxvcLWTWnwJXsiHHhmxC4',
    appId: '1:1038468137679:android:0f51762c5fd84c37456dba',
    messagingSenderId: '1038468137679',
    projectId: 'careermatebd',
    storageBucket: 'careermatebd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFArvbBLDOWRWSEqKoPUjHJEHEgZUw818',
    appId: '1:1038468137679:ios:8ce3e2806d162761456dba',
    messagingSenderId: '1038468137679',
    projectId: 'careermatebd',
    storageBucket: 'careermatebd.firebasestorage.app',
    iosBundleId: 'com.khokan.careermatebd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFArvbBLDOWRWSEqKoPUjHJEHEgZUw818',
    appId: '1:1038468137679:ios:8ce3e2806d162761456dba',
    messagingSenderId: '1038468137679',
    projectId: 'careermatebd',
    storageBucket: 'careermatebd.firebasestorage.app',
    iosBundleId: 'com.khokan.careermatebd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOPKrLPVGFQ9oPBdwPltb3W2XKNBvopF0',
    appId: '1:1038468137679:web:ac6cbeaa7f6d6f4f456dba',
    messagingSenderId: '1038468137679',
    projectId: 'careermatebd',
    authDomain: 'careermatebd.firebaseapp.com',
    storageBucket: 'careermatebd.firebasestorage.app',
  );
}
